theme: minima
title: 3OLEN - Projet 31
description: Informations et ressources sur le projet 31 de la promo 3OLEN de l'école ORT LYON.

collections:
  final:
    output: true
    permalink: /final/:slug
  intermediary_deliverables:
    output: true
    permalink: /livrables-intermediaires/:slug
  roadmap:
    output: true
    permalink: /:collection/:slug
  specifications:
    output: true
    permalink: /:collection/:slug
  technical_requests:
    output: true
    permalink: /contraintes_techniques/:slug
  project_helps:
    output: true
    permalink: /aides-projet/:slug

######### Configurations non-modifiables #########
##################################################
#
#lsi: false
#safe: true
#source: [your repo's top level directory]
#incremental: false
#highlighter: rouge
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge
